---
bindings:
    dvs_server: tcp://post.ndovloket.nl:7660
    client_server: tcp://151.80.159.178:8120
    injector_server: tcp://151.80.159.178:8140

logging:
    log_config: config/logging.yaml
...
